version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "shopping-list-cloud"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rdac65w3uh2p"
s3_prefix = "shopping-list-cloud"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "shopping-list-cloud"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rdac65w3uh2p"
s3_prefix = "shopping-list-cloud"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
